import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState} from 'react'
export default function Home() {
  const [warningHead, setWarningHead] = useState("↓Enter Your Link↓");
  return (
    <>
      <Head>
        <title>AYARS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.mainHeading}>Amey's Youtube Audience Retention System</h1>
        <h3>A Bot For Gaining Audience Retention On Youtube</h3>
        <h4 className={styles.warningHead}>{warningHead}</h4>
        <input type="text" className={styles.youtubeLinkInp} placeholder="Enter Your Youtube Link Here"/>
        <br />
        <button className={styles.mainButton}>Let's Go!</button>
      </main>
    </>
  )
}
